services:
  # Main backend web service (free tier)
  - type: web
    name: bartleby-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt 
    startCommand: cd backend && python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_VERSION
        value: 18.x
      - key: DATABASE_URL
        fromDatabase:
          name: bartlebySQL
          property: connectionString
      - key: NEON_DATABASE_URL
        sync: false  
      - key: OPENAI_API_KEY
        sync: false
      - key: STORAGE_BACKEND
        value: "generic"
      - key: BLOB_READ_WRITE_TOKEN
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_S3_EXPRESS_BUCKET
        sync: false
      - key: AWS_REGION
        value: "us-west-2"
      - key: CORS_ORIGINS
        value: "https://instantory.vercel.app,https://hocomnia.com,https://www.hocomnia.com,https://bartleby.vercel.app,http://localhost:3000,https://accounts.google.com,https://*.googleapis.com"
      - key: CORS_ENABLED
        value: "true"
      - key: ALLOW_CREDENTIALS
        value: "true"
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: PUBLIC_BACKEND_URL
        value: "https://bartleby-backend.onrender.com"
      - key: FRONTEND_URL
        value: "https://hocomnia.com"
      - key: VERCEL_URL
        value: "https://bartleby.vercel.app"
      - key: DATA_DIR
        value: "./data"
      - key: UPLOADS_DIR
        value: "./data/uploads"
      - key: INVENTORY_IMAGES_DIR
        value: "./data/images/inventory"
      - key: EXPORTS_DIR
        value: "./data/exports"
      - key: DOCUMENT_DIRECTORY
        value: "./data/documents"
      - key: LOG_LEVEL
        value: "info"
      - key: ADMIN_PASSWORD
        sync: false

# Free Postgres database
databases:
  - name: bartlebySQL
    plan: free
