# Service configuration for the backend API
services:
  - type: web
    name: instantory # Service name on Render
    runtime: python
    buildCommand: cd backend && pip install -r requirements.txt  # Install dependencies
    startCommand: cd backend && hypercorn server:app --bind 0.0.0.0:$PORT --access-log -  # Start server
    envVars:
      # Runtime configuration
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        sync: false

      # Database configuration (managed by Render)
      - key: DATABASE_URL
        fromDatabase:
          name: instantory_sql
          property: connectionString

      # Security and CORS settings
      - key: CORS_ENABLED
        value: "true"
      - key: ALLOW_CREDENTIALS
        value: "true"
      - key: CORS_ORIGIN
        value: https://bartleby.vercel.app

      # API configuration
      - key: PUBLIC_BACKEND_URL
        value: https://instantory.onrender.com

      # Frontend URL for CORS
      - key: VERCEL_URL
        value: "https://bartleby.vercel.app"

      # Vercel Blob Storage
      - key: BLOB_READ_WRITE_TOKEN
        sync: false
      # OpenAI Configuration (required for AI processing)
      - key: OPENAI_API_KEY
        sync: false  # This will prompt for the value during deployment
        
databases:
  - name: instantory_sql
    databaseName: bartleby_sql
    plan: free
    ipAllowList: []  # Allow all IPs for development

healthCheckPath: /healthz