# Service configuration for the backend API
services:
  - type: web
    name: instantory # Service name on Render
    runtime: python
    buildCommand: cd backend && pip install -r requirements.txt  # Install dependencies
    startCommand: cd backend && hypercorn server:app --bind 0.0.0.0:$PORT --access-log -  # Start server
    envVars:
      # Runtime configuration
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: "443"

      # Database configuration (managed by Render)
      - key: DATABASE_URL
        fromDatabase:
          name: bartlebyGRE
          property: connectionString

      # Security and CORS settings
      - key: CORS_ENABLED
        value: "true"
      - key: ALLOW_CREDENTIALS
        value: "true"
      - key: CORS_ORIGIN
        value: https://bartleby.vercel.app

      # API configuration
      - key: PUBLIC_BACKEND_URL
        value: https://bartleby.onrender.com

      # Frontend URL for CORS
      - key: VERCEL_URL
        value: "https://bartleby.vercel.app"

      # Vercel Blob Storage
      - key: BLOB_READ_WRITE_TOKEN
        value: "vercel_blob_rw_s5xuxXH6T3fDx9Oz_AdnmR7yE2uQjnt1cWInfUzpXQdtrpS"

      # OpenAI Configuration (required for AI processing)
      - key: OPENAI_API_KEY
        sync: false  # This will prompt for the value during deployment

# Database configuration
databases:
  - name: bartlebyGRE
    databaseName: bartlebyGRE
    plan: free
    ipAllowList: []  # Allow all IPs for development
