services:
  # Define the main web service (Python application)
  - type: web
    name: bartleby-backend
    runtime: python
    buildCommand: pip install -r requirements.txt 
    startCommand: cd backend && python server.py
    envVars:
      - key: PYTHONPATH
        value: "/backend"
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_VERSION
        value: 18.x
      - key: DATABASE_URL
        fromDatabase:
          name: bartlebySQL
          property: connectionString
      - key: NEON_DATABASE_URL
        sync: false  
        # Set this in the Render dashboard. 
      - key: OPENAI_API_KEY
        sync: false
      # Storage configuration
      - key: STORAGE_BACKEND
        value: "generic"
      - key: BLOB_READ_WRITE_TOKEN
        sync: false
      # AWS S3 configuration (optional)
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_S3_EXPRESS_BUCKET
        sync: false
      - key: AWS_REGION
        value: "us-west-2"
      # CORS and security
      - key: CORS_ORIGINS
        value: "https://hocomnia.com,https://bartleby.vercel.app,http://localhost:3000"
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      # Paths and URLs
      - key: PUBLIC_BACKEND_URL
        value: "https://bartleby-backend.onrender.com"
      - key: FRONTEND_URL
        value: "https://hocomnia.com"
      - key: VERCEL_URL
        value: "https://bartleby.vercel.app"
      # Data directories
      - key: DATA_DIR
        value: "./data"
      - key: UPLOADS_DIR
        value: "./data/uploads"
      - key: INVENTORY_IMAGES_DIR
        value: "./data/images/inventory"
      - key: EXPORTS_DIR
        value: "./data/exports"
      - key: DOCUMENT_DIRECTORY
        value: "./data/documents"
      # Logging
      - key: LOG_LEVEL
        value: "info"
      - key: ADMIN_PASSWORD
        sync: false
  
  # Database initialization service
  - type: web
    name: bartleby-db-init
    runtime: node
    buildCommand: cd backend && npm install --production
    predeployCommand: cd backend && node scripts/init_db.js
    startCommand: cd backend && npm run start
    envVars:
      - key: NODE_VERSION
        value: 22.x
      - key: DATABASE_URL
        fromDatabase:
          name: bartlebySQL
          property: connectionString
      - key: NEON_DATABASE_URL
        sync: false
      - key: STORAGE_BACKEND
        value: "generic"
      - key: BLOB_READ_WRITE_TOKEN
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_S3_EXPRESS_BUCKET
        sync: false
      - key: AWS_REGION
        value: "us-west-2"
      # CORS and frontend URLs (required for consistent configuration)
      - key: CORS_ORIGINS
        value: "https://hocomnia.com,https://bartleby.vercel.app,http://localhost:3000"
      - key: PUBLIC_BACKEND_URL
        value: "https://bartleby-backend.onrender.com"
      - key: FRONTEND_URL
        value: "https://hocomnia.com"
      
  # Background worker for processing tasks
  - type: worker
    name: bartleby-worker
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: "cd backend && python -m scripts.setup_user_storage"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: bartlebySQL
          property: connectionString
      - key: NEON_DATABASE_URL
        sync: false
      - key: STORAGE_BACKEND
        value: "generic"
      - key: BLOB_READ_WRITE_TOKEN
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_S3_EXPRESS_BUCKET
        sync: false
      - key: AWS_REGION
        value: "us-west-2"
      - key: DATA_DIR
        value: "./data"
      # CORS and frontend URLs (required for consistent configuration)
      - key: CORS_ORIGINS
        value: "https://hocomnia.com,https://bartleby.vercel.app,http://localhost:3000"
      - key: PUBLIC_BACKEND_URL
        value: "https://bartleby-backend.onrender.com"
      - key: FRONTEND_URL
        value: "https://hocomnia.com"

# Define the database
databases:
  - name: bartlebySQL
    plan: free
