services:
  # Main backend web service (free tier)
  - type: web
    name: bartleby-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 60 --worker-class=uvicorn.workers.UvicornWorker backend.server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_VERSION
        value: 18.x
      - key: DATABASE_URL
        fromDatabase:
          name: bartlebySQL
          property: connectionString
      - key: NEON_DATABASE_URL
        sync: false  
      - key: OPENAI_API_KEY
        sync: false
      - key: STORAGE_BACKEND
        value: "vercel"
      - key: BLOB_READ_WRITE_TOKEN
        sync: false
      - key: QDRANT_URL
        value: "https://a155b5ab-3dca-44ae-a3b7-7c8e0c472bbd.europe-west3-0.gcp.cloud.qdrant.io:6333"
      - key: QDRANT_API_KEY
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_S3_EXPRESS_BUCKET
        sync: false
      - key: AWS_REGION
        value: "us-west-2"
      - key: CORS_ENABLED
        value: "true"             
      - key: ALLOW_CREDENTIALS
        value: "true"
      - key: JWT_SECRET
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: PUBLIC_BACKEND_URL
        value: "https://bartleby-backend-mn96.onrender.com"
      - key: GOOGLE_REDIRECT_URI
        value: "https://bartleby-backend-mn96.onrender.com/api/auth/google/callback"
      - key: FRONTEND_URL
        value: "https://hocomnia.com"
      - key: VERCEL_URL
        value: "https://bartleby.vercel.app"
      - key: CORS_ORIGINS
        value: "https://hocomnia.com,https://www.hocomnia.com
        -
      - key: DATA_DIR
        value: "./data"
      - key: UPLOADS_DIR
        value: "./data/uploads"
      - key: INVENTORY_IMAGES_DIR
        value: "./data/images/inventory" 
      - key: EXPORTS_DIR
        value: "./data/exports"
      - key: DOCUMENT_DIRECTORY
        value: "./data/documents"
      - key: LOG_LEVEL
        value: "info"
      - key: ADMIN_PASSWORD
        sync: false
      - key: DEBUG
        value: "false"
      - key: PYTHONPATH
        value: "."
      - key: BACKEND_URL
        value: "https://bartleby-backend-mn96.onrender.com"
      - key: ENVIRONMENT
        value: "production"
      - key: NODE_ENV
        value: "production"

# Free Postgres database
databases:
  - name: bartlebySQL
    plan: free
