# Service configuration for the backend API
services:
  - type: web
    name: instantory-api  # Service name on Render
    runtime: python
    buildCommand: cd backend && pip install -r requirements.txt  # Install dependencies
    startCommand: cd backend && hypercorn server:app --bind 0.0.0.0:$PORT --access-log -  # Start server
    envVars:
      # Runtime configuration
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        sync: true  # Let Render manage the port

      # Database configuration (managed by Render)
      - key: DATABASE_URL
        fromDatabase:
          name: instantory_sql
          property: connectionString

      # Security and CORS settings
      - key: CORS_ENABLED
        value: "true"
      - key: ALLOW_CREDENTIALS
        value: "true"
      - key: CORS_ORIGIN
        value: https://instantory.vercel.app,https://instantory-dhj0hu4yd-demothedreads-projects.vercel.app

      # API configuration
      - key: PUBLIC_BACKEND_URL
        value: https://instantory-api.onrender.com

      # Frontend URL for CORS
      - key: VERCEL_URL
        value: "https://instantory-6pl2dnzgn-demothedreads-projects.vercel.app"

# Database configuration
databases:
  - name: instantory_sql
    databaseName: instantory_sql
    plan: free
    ipAllowList: []  # Allow all IPs for development
